# Import existing mappings
from .fenkai_nanobanana_pro import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY
from .fenkai_gemini import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY
from .gemini_smart_pad import NODE_CLASS_MAPPINGS as PAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PAD_DISPLAY

# --- UPDATE THIS LINE ---
# Changed "gemini_unpad" to "unpadder" to match your new filename
from .unpadder import NODE_CLASS_MAPPINGS as UNPAD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as UNPAD_DISPLAY

# Merge everything
NODE_CLASS_MAPPINGS = {
    **IMAGE_MAPPINGS, **TEXT_MAPPINGS, 
    **PAD_MAPPINGS, **UNPAD_MAPPINGS
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_DISPLAY, **TEXT_DISPLAY, 
    **PAD_DISPLAY, **UNPAD_DISPLAY
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']