from .fenkai_nanobanana_pro import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY
from .fenkai_gemini import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY

# Merge the mappings
NODE_CLASS_MAPPINGS = {**IMAGE_MAPPINGS, **TEXT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**IMAGE_DISPLAY, **TEXT_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']